import { motion } from "framer-motion";
import { Github, ExternalLink } from "lucide-react";
const projects=[
{title:"Aligno — OKR SaaS",subtitle:"Multi-tenant performance & OKR platform",description:"Organization, department and team management with role-based access, OKR workflows, analytics, approval pipelines, notifications, subscription gating and Razorpay payments.",tech:["Next.js","TypeScript","Prisma","PostgreSQL"],github:"https://github.com/aviralnull/okr_system",live:"https://www.asynccoder.in/sign-in",image:"https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=80"},
{title:"Mystery Feedback",subtitle:"Anonymous feedback platform",description:"Personalized feedback links, authentication, AI-assisted suggestions, notifications and dashboards for managing anonymous feedback.",tech:["Next.js","OpenAI","PostgreSQL"],github:"https://github.com/aviralnull/Feedback_system",live:"https://feedback-system-gold.vercel.app/",image:"https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80"},
{title:"Chess Engine — LLD",subtitle:"Modular game architecture",description:"Low-level design implementation covering chess rules, move validation, board state and extensible object-oriented architecture.",tech:["C++","OOP","SOLID","Patterns"],github:"https://github.com/aviralnull/LLD_Content/tree/main/Chess",image:"https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=1200&q=80"},
{title:"Spotify Clone — LLD",subtitle:"Music platform system design",description:"Object-oriented low-level design exploring a modular Spotify-like system and domain modelling patterns.",tech:["C++","LLD","OOP","Design Patterns"],github:"https://github.com/aviralnull/LLD_Content/tree/main/Spotify",image:"https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80"},
{title:"VelocityDB",subtitle:"Custom C++ database engine",description:"File-based storage, page management, custom record formats and CRUD operations with a React + Electron desktop interface and live query workflow.",tech:["C++","Electron","React","IPC"],github:"https://github.com/aviralnull/Database",image:"https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=80"},
{title:"TLS Chat System",subtitle:"Secure multithreaded messaging",description:"TCP socket based chat application using OpenSSL/TLS with concurrent communication and thread-safe messaging.",tech:["C","TCP","OpenSSL","Threads"],github:"https://github.com/aviralnull/Tls_based_chat_app",image:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80"}
];
const updateGlow = (e: React.MouseEvent<HTMLDivElement>) => {
  const el=e.currentTarget, r=el.getBoundingClientRect();
  const x=e.clientX-r.left, y=e.clientY-r.top;
  el.style.setProperty("--mouse-x", `${x}px`);
  el.style.setProperty("--mouse-y", `${y}px`);
  el.style.setProperty("--rotate-x", `${((y/r.height)-.5)*-5}deg`);
  el.style.setProperty("--rotate-y", `${((x/r.width)-.5)*5}deg`);
};
const resetGlow = (e: React.MouseEvent<HTMLDivElement>) => {
  e.currentTarget.style.setProperty("--rotate-x","0deg");
  e.currentTarget.style.setProperty("--rotate-y","0deg");
};

export const ProjectsSection=()=> <section id="projects" className="w-full max-w-7xl mx-auto px-6 py-24"><motion.div initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="mb-16"><span className="text-primary text-xs font-bold tracking-widest uppercase">Selected Work</span><h2 className="text-4xl md:text-6xl font-bold tracking-tight mt-3">Projects I'm <span className="text-gradient-primary">proud of.</span></h2><p className="text-muted-foreground max-w-2xl mt-5">From production SaaS products to database engines, networking systems and low-level design implementations.</p></motion.div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">{projects.map((project,i)=><motion.div key={project.title} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} transition={{delay:i*.06}} viewport={{once:true}} onMouseMove={updateGlow} onMouseLeave={resetGlow} className="project-card group relative overflow-hidden rounded-[1.8rem] min-h-[390px] shadow-xl border border-foreground/10"><img src={project.image} alt={project.title} className="absolute inset-0 w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"/><div className="absolute inset-0 bg-gradient-to-t from-[#050814] via-[#050814]/80 to-[#050814]/10"/><div className="relative z-10 h-full min-h-[390px] p-7 flex flex-col justify-end"><div className="text-primary-foreground/65 text-sm font-medium mb-2">{project.subtitle}</div><h3 className="text-white text-2xl font-extrabold mb-3">{project.title}</h3><p className="text-white/75 text-sm leading-relaxed mb-5">{project.description}</p><div className="flex flex-wrap gap-2 mb-5">{project.tech.map(t=><span key={t} className="text-xs px-3 py-1 rounded-full bg-white/10 text-white border border-white/15 backdrop-blur">{t}</span>)}</div><div className="flex gap-3"><a href={project.github} target="_blank" rel="noreferrer" className="project-action"><Github size={16}/> Code</a>{project.live&&<a href={project.live} target="_blank" rel="noreferrer" className="project-action primary"><ExternalLink size={16}/> Live Demo</a>}</div></div></motion.div>)}</div></section>;
