import { motion } from "framer-motion";
import { Trophy, Medal, BadgeCheck } from "lucide-react";
const achievements=[{title:"LeetCode",subtitle:"1860 rating • 500+ problems solved",icon:Trophy},{title:"Codeforces",subtitle:"1159 rating",icon:Medal},{title:"Saras AI Hackathon",subtitle:"Winner and multiple college hackathon achievements",icon:BadgeCheck}];
const updateGlow=(e:React.MouseEvent<HTMLDivElement>)=>{const el=e.currentTarget,r=el.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;el.style.setProperty("--mouse-x",`${x}px`);el.style.setProperty("--mouse-y",`${y}px`);el.style.setProperty("--rotate-x",`${((y/r.height)-.5)*-4}deg`);el.style.setProperty("--rotate-y",`${((x/r.width)-.5)*4}deg`)};
const resetGlow=(e:React.MouseEvent<HTMLDivElement>)=>{e.currentTarget.style.setProperty("--rotate-x","0deg");e.currentTarget.style.setProperty("--rotate-y","0deg")};
const TestimonialsSection=()=> <section id="testimonials" className="max-w-7xl mx-auto px-6 py-24">
<motion.div initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="mb-14 text-center"><h2 className="text-3xl md:text-5xl font-bold">Achievements & <span className="text-gradient-primary">Competitive Programming</span></h2><p className="text-muted-foreground max-w-2xl mx-auto mt-4">A few milestones that reflect my interest in problem solving, competitive programming and building.</p></motion.div>
<div className="grid grid-cols-1 md:grid-cols-3 gap-6">{achievements.map((a,i)=>{const Icon=a.icon;return <motion.div key={a.title} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} transition={{delay:i*.1}} viewport={{once:true}} onMouseMove={updateGlow} onMouseLeave={resetGlow} className="premium-hover-card achievement-card glass-panel p-8 rounded-3xl border border-foreground/10"><div className="achievement-icon w-14 h-14 rounded-2xl bg-primary/10 text-primary flex items-center justify-center mb-6"><Icon className="w-7 h-7"/></div><h3 className="text-xl font-bold mb-2">{a.title}</h3><p className="text-muted-foreground text-sm">{a.subtitle}</p><div className="achievement-shine"/></motion.div>})}</div>
</section>;
export default TestimonialsSection;