import { motion, useScroll, useSpring } from "framer-motion";
import { useRef } from "react";
const timeline=[
{year:"2025",title:"Software Developer Intern",company:"AWDH Technology",description:"Worked on production web applications across feature development, debugging, testing and deployment while collaborating through the software development lifecycle."},
{year:"2025",title:"Builder & Competitive Programmer",company:"Meta Hacker Cup • Saras AI Hackathon",description:"Qualified for Meta Hacker Cup 2025 Round 2 with ranks 2056 and 1309, while winning the Saras AI Hackathon and continuing to build systems projects."},
{year:"2023 – Present",title:"Computer Science Journey",company:"IIIT Agartala",description:"Studying algorithms, operating systems, databases and computer networks while building full-stack products, C++ systems and low-level design implementations."}
];
const updateCardGlow=(e:React.MouseEvent<HTMLDivElement>)=>{const el=e.currentTarget,r=el.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;el.style.setProperty("--mouse-x",`${x}px`);el.style.setProperty("--mouse-y",`${y}px`);el.style.setProperty("--rotate-x",`${((y/r.height)-.5)*-3}deg`);el.style.setProperty("--rotate-y",`${((x/r.width)-.5)*3}deg`)};
const resetCardGlow=(e:React.MouseEvent<HTMLDivElement>)=>{e.currentTarget.style.setProperty("--rotate-x","0deg");e.currentTarget.style.setProperty("--rotate-y","0deg")};
export const CareerTimeline=()=>{const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start 75%","end 35%"]});const scaleY=useSpring(scrollYProgress,{stiffness:100,damping:30});return <section id="career" className="max-w-6xl mx-auto px-6 py-24"><motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="mb-16 text-center"><span className="text-primary text-xs font-bold tracking-widest uppercase">The path so far</span><h2 className="text-4xl md:text-5xl font-bold mt-3">Experience & <span className="text-gradient-primary">Journey</span></h2></motion.div><div ref={ref} className="journey-line relative">{timeline.map((item,i)=><motion.article key={item.title} initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.35}} className={`journey-item ${i%2?"right":"left"}`}><div className="journey-dot"><span/></div><div onMouseMove={updateCardGlow} onMouseLeave={resetCardGlow} className="journey-card glass-panel p-7 rounded-3xl border border-foreground/10"><span className="text-primary font-bold text-sm">{item.year}</span><h3 className="text-xl md:text-2xl font-bold mt-2">{item.title}</h3><div className="text-primary/80 font-medium mt-1 mb-4">{item.company}</div><p className="text-muted-foreground leading-relaxed">{item.description}</p></div></motion.article>)}<motion.div style={{scaleY,transformOrigin:"top"}} className="journey-progress"/></div></section>}
